In [4]:
import numpy as np

In [1]:
def Rx(q):
    T = np.array([[1,         0,          0, 0],
                  [0, np.cos(q), -np.sin(q), 0],
                  [0, np.sin(q),  np.cos(q), 0],
                  [0,         0,          0, 1]], dtype=float)
    return T


def Ry(q):
    T = np.array([[ np.cos(q), 0, np.sin(q), 0],
                  [         0, 1,         0, 0],
                  [-np.sin(q), 0, np.cos(q), 0],
                  [         0, 0,         0, 1]], dtype=float)
    return T


def Rz(q):
    T = np.array([[np.cos(q), -np.sin(q), 0, 0],
                  [np.sin(q),  np.cos(q), 0, 0],
                  [        0,          0, 1, 0],
                  [        0,          0, 0, 1]], dtype=float)
    return T


def Tx(x):
    T = np.array([[1, 0, 0, x],
                  [0, 1, 0, 0],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]], dtype=float)
    return T


def Ty(y):
    T = np.array([[1, 0, 0, 0],
                  [0, 1, 0, y],
                  [0, 0, 1, 0],
                  [0, 0, 0, 1]], dtype=float)
    return T


def Tz(z):
    T = np.array([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, z],
                  [0, 0, 0, 1]], dtype=float)
    return T

In [5]:
def DH(d, theta, a, alpha):
    A = Rz(theta) @ Tz(d) @ Tx(a) @ Rx(alpha)
    return A

In [31]:
# robot parameters, links (m)
l1 = 0.346
l2 = 0.324
l3 = 0.312
l4 = 1.075
l5 = 0.225
l6 = 1.280
l7 = 0.215
d6 = 0.3
q = [0,0,0,0,0,0]

In [27]:
d_p= np.array([l1, 0, 0, l3, 0, d6])
th_p = np.array([np.pi/2, 0, np.pi/2, np.pi/2, 0, 0])
a_p = np.array([0, l2, 0, 0, 0, 0])
al_p = np.array([np.pi/2, 0, np.pi/2, np.pi/2, np.pi/2, 0])

In [55]:
def FK(q_cor):
    Matrix = np.eye(4)

    for i, q in enumerate(q_cor):
      Matrix = Matrix @ DH(d_p[i], th_p[i]+q, a_p[i], al_p[i])

    return Matrix


In [9]:
def FKold(q):
  Matrix = Tz(l1) @ Rz(q[0]) @ Tz(l2) @ Tx(l3) @ Ry(q[1]) @ Tx(l4) @ Ry(q[2]) @ Tz(l5) @ Tx(l6) @ Ry(q[3]) @ Rz(q[4]) @ Ry(q[5])

  return Matrix

In [41]:
def FK3(q):
  Matrix =  Rz(q[0]) @ Tz(l1) @ Ry(q[1]) @ Tx(l2) @ Ry(q[2]) @ Tx(l3)

  return Matrix

In [47]:
def get_cosine_law_angle(a, b, c):
  # given all sides of a triangle a, b, c
  # calculate angle gamma between sides a and b using cosine law
  cos_gamma = (a*a + b*b - c*c) / (2*a*b)
  sin_gamma = np.sqrt(1 - cos_gamma * cos_gamma)
  gamma = np.arctan2(sin_gamma, cos_gamma)

  return gamma

def first_angles(wrist_center):
    x, y, z = wrist_center
    theta1 = np.arctan2(y, x)- np.pi/2
    r = np.sqrt(x**2+y**2)
    h = z - l1
    p = np.sqrt(r**2+h**2)
    print(z, l1)
    alpha = np.arctan2(h, r)
    gamma1 = get_cosine_law_angle(l2, p, l3)
    print(gamma1, alpha)
    theta2 = gamma1 - alpha
    gamma2 = get_cosine_law_angle(l2, l3, p)
    theta3 = np.pi - gamma2
    return theta1, theta2, theta3



In [59]:
q = [0,  np.pi/8, np.pi/6, 0]
print(q)
first_angles(FK(q)[:3,3])

[0, 0.39269908169872414, 0.5235987755982988, 0]
0.7175156742571543 0.346
0.25674378573161305 0.6494428674303375


(0.0, -0.3926990816987245, 0.5235987755982987)

In [40]:
FK(q)

array([[-6.12323400e-17,  1.00000000e+00,  1.23259516e-32,
         1.98392781e-17],
       [-1.00000000e+00, -6.12323400e-17,  1.22464680e-16,
         3.24000000e-01],
       [ 1.22464680e-16,  0.00000000e+00,  1.00000000e+00,
         3.46000000e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [ ]:
q= [0, np.pi/6, 0]

In [ ]:
FK3(q)

array([[ 0.8660254 ,  0.        ,  0.5       ,  0.55079216],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-0.5       ,  0.        ,  0.8660254 ,  0.028     ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
FK3(first_angles(FK3(q)[:3,3]))

array([[ 0.86591962, -0.5       ,  0.01353576,  0.47165243],
       [ 0.49993892,  0.8660254 ,  0.00781487,  0.27230866],
       [-0.01562975,  0.        ,  0.99987785,  0.56661732],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
def IK(T):
  x, y, z = T[:3,3]
  q1 = np.arctan2(y, x)
  r = np.sqrt(x**2+y**2)
  d = np.sqrt(l5**2+l6**2)
  HY = z-l1-l2
  KY = r-l3
  HM = d+l7
  KM = l4
  KH = np.sqrt(KY**2+HY**2)
  gamma1 = np.arctan2(HY, KY)
  gamma2 = np.arccos((KM**2+KH**2-HM**2)/(2*KH*KM))
  q2=gamma1-gamma2
  gamma3 = np.arccos((KM**2+HM**2-KH**2)/(2*HM*KM))
  q3 = np.pi - gamma3
  return q1,q2,q3


nq = np.array([1,0,0,0,1,1])
IK(FK(nq))

(1.0, -0.4069853701364795, 0.8509240633968238)